In [1]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload


import pynarrative as pn

import pandas as pd
import altair as alt

print("Percorso libreria caricata:", pn.__file__)

Percorso libreria caricata: /home/lorenzo/Scrivania/Sincronizzato con Nextcloud/Università/1. Triennale informatica umanistica (L-10) UniPi/TERZO ANNO/altro/tirocinio/pynarrative/codice/pynarrative-dev/pynarrative/src/pynarrative/__init__.py

In [2]:
import numpy as np
import string

np.random.seed(42)

len = 10
valori = np.random.randint(0, 100, len)

dati_categorie = pd.DataFrame({
    "categorie": [i for i in string.ascii_uppercase[:len]],
    "valori": valori
})


dati_categorie

  categorie  valori
0         A      51
1         B      92
2         C      14
3         D      71
4         E      60
5         F      20
6         G      82
7         H      86
8         I      74
9         J      74

*Historical Template*

In [3]:
from pynarrative import HistoricalTemplate as HT

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = HT
    )

    #Chiamata dei metodi

    .mark_bar(
        cornerRadiusTopLeft = 7,
        cornerRadiusTopRight = 7,

    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True))
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte384db5
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = 50,
    )

    .add_highlight("B")
    


    .render()
)

storia

Single value = 50

alt.VConcatChart(...)

*Minimal Template*

In [4]:
from pynarrative import MinimalTemplate as MT

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = MT
    )

    #Chiamata dei metodi

    .mark_bar(
        cornerRadiusTopLeft = 7,
        cornerRadiusTopRight = 7,

    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True))
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = 50,
    )

    .add_highlight("B")
    


    .render()
)

storia

Single value = 50

alt.VConcatChart(...)

*Environmental Template*

In [5]:
from pynarrative import EnvironmentalTemplate as ET

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = ET
    )

    #Chiamata dei metodi

    .mark_bar(
        cornerRadiusTopLeft = 7,
        cornerRadiusTopRight = 7,

    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True))
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte384db5
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = 50,
    )

    .add_highlight("B")
    


    .render()
)

storia

Single value = 50

alt.VConcatChart(...)

**Template monocromatici**

*Blue*

In [6]:
from pynarrative import BlueTemplate as BT

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 650,
        height = 500,
        template = BT
    )

    #Chiamata dei metodi

    .mark_bar(
        # cornerRadiusBottomRight = 7,
        # cornerRadiusTopRight = 7,
        cornerRadiusEnd = 7
    )

    .encode( #encoding dei dati
        y = alt.Y("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        x = alt.X("valori:Q", title = "Valore", axis = alt.Axis(grid = True), scale = alt.Scale(domain = [0, 100]))
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dx = 20
    )

    .add_line(
        orientation = "vertical",
        math = "mean",
        value = dati_categorie["valori"],
        label_dx = -15,
        label_dy = -5
    )

    .add_highlight("B")
    


    .render()
)

storia

Mean = 62.4

alt.VConcatChart(...)

*Green*

In [7]:
from pynarrative import GreenTemplate as GT

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = GT
    )

    #Chiamata dei metodi

    .mark_bar(
        cornerRadiusTopLeft = 7,
        cornerRadiusTopRight = 7,

    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True))
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )


    .add_next_steps( #prossima parte della storia
        steps = ["Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt.", "ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat."],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )

    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        value = dati_categorie["valori"].tolist(),
        math = "mean",
        color = "green",
        label_text = "Media 62.4",
        label_font_size = 16,
        label_font_weight = "bold"
    )

    .add_line(
        value = dati_categorie["valori"].tolist(),
        math = "median",
        color = "darkblue",
        label_text = "Mediana 72.5",
        label_font_size = 16,
        label_font_weight = "bold"
    )

    .add_highlight("B")
    


    .render()
)

storia

Mean = 62.4
Median = 72.5

alt.VConcatChart(...)

*BeigeTemplate*

In [8]:
from pynarrative import BeigeTemplate


storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = BeigeTemplate
    )

    #Chiamata dei metodi

    .mark_bar(
        # cornerRadiusTopLeft = 7,
        # cornerRadiusTopRight = 7,
        cornerRadiusEnd = 10
    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True)),
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = dati_categorie["valori"].tolist(),
        math = "max",
        color = "green",
        label_text = "Massimo",
    )

    .add_line(
        orientation = "horizontal",
        value = dati_categorie["valori"].tolist(),
        math = "min",
        label_text = "Minimo"
    )


    .add_highlight("B")
    


    .render()
)

storia

Max = 92
Min = 14

alt.VConcatChart(...)

*RedTemplate*

In [9]:
from pynarrative import GreyTemplate


storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = GreyTemplate
    )

    #Chiamata dei metodi

    .mark_bar(
        # cornerRadiusTopLeft = 7,
        # cornerRadiusTopRight = 7,
        cornerRadiusEnd = 10
    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True)),
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = dati_categorie["valori"].tolist(),
        math = "max",
        color = "green",
        label_text = "Massimo",
    )

    .add_line(
        orientation = "horizontal",
        value = dati_categorie["valori"].tolist(),
        math = "min",
        label_text = "Minimo"
    )


    .add_highlight("B")
    


    .render()
)

storia

Max = 92
Min = 14

alt.VConcatChart(...)

**Template bicolore**

*BlueBeigeTemplate*

In [10]:
from pynarrative import BlueBeigeTemplate

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = BlueBeigeTemplate
    )

    #Chiamata dei metodi

    .mark_bar(
        cornerRadiusTopLeft = 7,
        cornerRadiusTopRight = 7,
    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True))
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = 50,
    )

    .add_highlight("B")


    .render()
)

storia

Single value = 50

alt.VConcatChart(...)

*BeigeBlueTemplate*

In [11]:
from pynarrative import BeigeBlueTemplate as BBT

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = BBT
    )

    #Chiamata dei metodi

    .mark_bar(
        cornerRadiusTopLeft = 7,
        cornerRadiusTopRight = 7,

    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True))
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum \n dolor sit amet",
        position = "left",
        font_weight = "bold",
        font_style = "italic"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte384db5
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = 50,
    )

    .add_highlight("B")
    


    .render()
)

storia

Single value = 50

alt.VConcatChart(...)

In [12]:
from pynarrative import GreyBrownTemplate as GBT


storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = GBT
    )

    #Chiamata dei metodi

    .mark_bar(
        # cornerRadiusTopLeft = 7,
        # cornerRadiusTopRight = 7,
        cornerRadiusEnd = 10
    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True)),
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = dati_categorie["valori"].tolist(),
        math = "mean",
        label_font_weight = "bold",
    )


    # .add_highlight("B")
    


    .render()
)

storia

Mean = 62.4

alt.VConcatChart(...)

In [13]:
from pynarrative import BrownGreyTemplate as BGT


storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie,
        width = 500,
        height = 300,
        template = BGT
    )

    #Chiamata dei metodi

    .mark_bar(
        # cornerRadiusTopLeft = 7,
        # cornerRadiusTopRight = 7,
        cornerRadiusEnd = 10
    )

    .encode( #encoding dei dati
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True)),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True)),
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_labels_chart(
        font_size = 20,
        font_weight = "bold",
        dy = 20
    )

    .add_line(
        orientation = "horizontal",
        value = dati_categorie["valori"].tolist(),
        math = "median",
        label_font_weight = "bold",
    )


    .add_highlight("B")
    


    .render()
)

storia

Median = 72.5

alt.VConcatChart(...)

**GRAFICI MULTI-SERIE**

In [14]:
np.random.seed(43)

len = 10

valori1 = np.random.randint(50, 100, len)
valori2 = np.random.randint(40, 150, len)
valori3 = np.random.randint(0, 60, len)
# valori4 = np.random.randint(0, 100, len)
# valori5 = np.random.randint(0, 100, len)

dati_categorie_multiserie = pd.DataFrame({
    "categorie": [i for i in string.ascii_uppercase[:len]],
    "valori1": valori1,
    "valori2": valori2,
    "valori3": valori3,
    # "valori4": valori4,
    # "valori5": valori5,
})


dati_categorie_multiserie

  categorie  valori1  valori2  valori3
0         A       54      127       35
1         B       50      104       53
2         C       99       75        4
3         D       71       90       36
4         E       66      115       48
5         F       67      129       53
6         G       77      105       12
7         H       52       74       24
8         I       96      115       47
9         J       80      106       32

In [15]:
dati_categorie_multiserie_long = dati_categorie_multiserie.melt(
    id_vars = "categorie",  # Colonna che rimane fissa
    value_vars = ["valori1", "valori2", "valori3"],#, "valori4", "valori5"],  # Colonne da trasformare
    var_name = "serie",  # Nome della nuova colonna categorica
    value_name = "valori"  # Nome della colonna con i valori
)

dati_categorie_multiserie_long.head()

  categorie    serie  valori
0         A  valori1      54
1         B  valori1      50
2         C  valori1      99
3         D  valori1      71
4         E  valori1      66

In [16]:
from pynarrative import BeigeBlueTemplate as BBT

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie_multiserie_long,
        width = 700,
        height = 400,
        template = BBT
    )

    #Chiamata dei metodi

    .mark_bar(
        # cornerRadiusTopLeft = 7,
        # cornerRadiusTopRight = 7,
        # size = 15
    )

    .encode(
        x = alt.X(
            "categorie:N",
            title = "Categoria",
            axis = alt.Axis(grid = True),
            scale = alt.Scale(paddingInner = 0.3) #Spazio tra i gruppi
            ),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True)),
        color = alt.Color("serie:N", title = "Legenda"),

        xOffset = alt.XOffset(
            "serie:N",
            scale = alt.Scale(paddingInner = 0.1) #Spazio tra le barre del singolo gruppo
        )
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
        font_weight = "bold"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source(
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_line(
        orientation = "horizontal",
        math = "mean",
        value = dati_categorie_multiserie["valori1"].tolist(),
        color = "darkblue",
        label_text = "Media serie 1 (71,2)",
        label_font_weight = "bold",
        label_font_size = 16,
    )

    .add_line(
        orientation = "horizontal",
        math = "mean",
        value = dati_categorie_multiserie["valori2"].tolist(),
        color = "darkorange",
        label_text = "Media serie 2 (104)",
        label_font_weight = "bold",
        label_font_size = 16
    )

    .add_line(
        orientation = "horizontal",
        math = "mean",
        value = dati_categorie_multiserie["valori3"].tolist(),
        color = "darkgreen",
        label_text = "Media serie 3 (34,4)",
        label_font_weight = "bold",
        label_font_size = 16
    )

    .add_highlight("C")


    .render()
)

storia

Mean = 71.2
Mean = 104.0
Mean = 34.4

alt.VConcatChart(...)

In [17]:
from pynarrative import BlueTemplate as BT

storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = dati_categorie_multiserie_long,
        width = 800,
        height = 500,
        template = BT
    )

    #Chiamata dei metodi

    .mark_line(
        point=True,
        interpolate = "cardinal"
        )


    .encode(
        x = alt.X("categorie:N", title = "Categoria", axis = alt.Axis(grid = True, labelAngle = 0 )),
        y = alt.Y("valori:Q", title = "Valore", axis = alt.Axis(grid = True)),
        color = alt.Color("serie:N", title = "Serie"),
        xOffset = "serie:N"  # Barre raggruppate
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "right",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_line(
        orientation = "horizontal",
        value = 50,
    )


    .render()
)

storia

Single value = 50

alt.VConcatChart(...)

In [18]:
np.random.seed(47)
valori1 = np.random.randint(50, 80, 20)
valori2 = np.random.randint(50, 100, 20)
valori3 = np.random.randint(50, 65, 20)

dati = pd.DataFrame({
    "valori1": valori1,
    "valori2": valori2,
    "valori3": valori3,
})

dati["indice"] = dati.index

dati = dati[["indice", "valori1", "valori2", "valori3"]]



dati.tail()

    indice  valori1  valori2  valori3
15      15       68       85       55
16      16       76       87       56
17      17       68       59       54
18      18       61       56       62
19      19       51       72       60

In [19]:
dati_long = dati.melt(id_vars='indice', 
                       var_name='serie', 
                       value_name='valore')

dati_long.head()

   indice    serie  valore
0       0  valori1      57
1       1  valori1      56
2       2  valori1      57
3       3  valori1      58
4       4  valori1      58

In [20]:
storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        # data = dati_long,
        data = dati,
        width = 700,
        height = 450,
        template = BBT
    )

    #Chiamata dei metodi

    # .mark_point()
    .mark_line(
        point = True,
        interpolate = "cardinal",
        # interpolate = "basis",
        # interpolate = "step",
        # interpolate = "step-before",
        # interpolate = "step-after",
        strokeDash=[10, 4]
    )

    .encode(
        x = alt.X("indice:Q", title = "Categoria", axis = alt.Axis(grid = True, labelAngle = 0 )),
        # y = alt.Y("valore:Q", title = "Valore", axis = alt.Axis(grid = True)),
        y = alt.Y("valori1:Q", title = "Valore", axis = alt.Axis(grid = True), scale = alt.Scale(domain=[0, 100])),
        # color = alt.Color("serie:N", title = "Serie"),
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .add_line(
        orientation = "horizontal",
        math = "mean",
        value = dati["valori1"]
    )

    .add_line(
        orientation = "horizontal",
        math = "min",
        value = dati["valori1"],
        color = "darkblue"
    )

    .add_line(
        orientation = "horizontal",
        math = "max",
        value = dati["valori1"],
        color = "darkgreen"
    )

    .render()
)

storia

Mean = 63.9
Min = 51
Max = 77

alt.VConcatChart(...)

In [41]:
np.random.seed(48)

x = np.random.randint(0, 100, 100)
y = np.random.randint(20, 100, 100)

coord = pd.DataFrame({
    "x": x,
    "y": y,
})

coord.tail()

     x   y
95  68  45
96  32  21
97  17  45
98  28  55
99  16  87

In [42]:
storia = (
    pn.Story(
    #Costruzione dell'oggetto di classe Story
        data = coord,
        width = 700,
        height = 450,
        template = GreyTemplate
    )

    #Chiamata dei metodi

    .mark_point()

    .encode(
        x = alt.X("x:Q", title = "Coord1", axis = alt.Axis(grid = True, labelAngle = 0 )),
        y = alt.Y("y:Q", title = "Coord2", axis = alt.Axis(grid = True), scale = alt.Scale(domain = [0, 120])),
    )
    

    .add_title( #titolo e sottotitolo
        title = "Grafico a barre con dati e categorie",
        subtitle = "Esempio di utilizzo di pynarrative",
        align = "center"
    )

    .add_context( #contesto, testo, spiegazione
        text = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.",
        position = "left",
    )

    .add_next_steps( #prossima parte della storia
        steps = ["NS1", "NS2"],
        title = "Next Steps", #
        position = "bottom" #
    )

    .add_source( #fonte
        text = "Fonte: dati di esempio",
        position = "bottom",
        align = "right"
    )


    .render()
)

storia

alt.VConcatChart(...)